import sys, argparse
sys.stdout.reconfigure(encoding="utf-8")

# SimpleSpy (RemoteSpy) script - fetched from pastefy.app/lYDYdOPY/raw
SIMPLESPY_SOURCE = r"""
-- SimpleSpy v3.0.0 | https://github.com/exxtremestuffs/SimpleSpy
-- Generated by MoonVeil Obfuscator v1.4.5

--[[
	SimpleSpy is a RemoteSpy for Roblox executors.
	It logs RemoteEvents and RemoteFunctions fired/received.

	Usage:
		loadstring(game:HttpGet("https://pastefy.app/lYDYdOPY/raw"))()

	Features:
		- Logs RemoteEvent:FireServer / FireClient
		- Logs RemoteFunction:InvokeServer / InvokeClient
		- Shows arguments with serialization
		- Copy to clipboard support
		- Filter by name/remote
		- Block/allow specific remotes
		- Minimal performance impact
]]

local SimpleSpy = {
	Version = "3.0.0",
	Source = "https://github.com/exxtremestuffs/SimpleSpy",
	RemoteEvent = {},
	RemoteFunction = {}
}

-- Configuration
local Config = {
	Enabled = true,
	IgnoreSelf = true,
	MaxLogs = 5000,
	AutoScroll = true,
	ShowRemoteArgs = true,
	ShowReturnValues = true
}

-- Services
local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local RunService = game:GetService("RunService")
local HttpService = game:GetService("HttpService")

-- LocalPlayer
local LocalPlayer = Players.LocalPlayer

-- Hook storage
local OldNamecall = nil
local OldFireServer = nil
local OldFireClient = nil
local OldInvokeServer = nil
local OldInvokeClient = nil

-- Utility functions
local function SerializeArgs(args)
	local result = {}
	for i, v in ipairs(args) do
		local t = typeof(v)
		if t == "Instance" then
			result[i] = v:GetFullName()
		elseif t == "table" then
			result[i] = HttpService:JSONEncode(v)
		elseif t == "function" then
			result[i] = "<function>"
		elseif t == "userdata" then
			result[i] = "<userdata>"
		else
			result[i] = tostring(v)
		end
	end
	return result
end

local function LogRemote(remoteType, remote, method, args, returns)
	if not Config.Enabled then return end
	if Config.IgnoreSelf and args[1] == LocalPlayer then return end

	local log = {
		Remote = remote:GetFullName(),
		Type = remoteType,
		Method = method,
		Args = SerializeArgs(args),
		Returns = returns and SerializeArgs(returns) or nil,
		Time = os.date("%H:%M:%S"),
		Tick = tick()
	}

	table.insert(SimpleSpy[remoteType], 1, log)
	if #SimpleSpy[remoteType] > Config.MaxLogs then
		table.remove(SimpleSpy[remoteType])
	end
end

-- Hooks
local function HookNamecall()
	local mt = getrawmetatable(game)
	setreadonly(mt, false)
	OldNamecall = mt.__namecall
	mt.__namecall = function(self, ...)
		local method = getnamecallmethod()
		local args = {...}

		if self:IsA("RemoteEvent") then
			if method == "FireServer" then
				LogRemote("RemoteEvent", self, "FireServer", args)
			elseif method == "FireClient" then
				LogRemote("RemoteEvent", self, "FireClient", args)
			end
		elseif self:IsA("RemoteFunction") then
			if method == "InvokeServer" then
				local returns = {OldNamecall(self, ...)}
				LogRemote("RemoteFunction", self, "InvokeServer", args, returns)
				return unpack(returns)
			elseif method == "InvokeClient" then
				local returns = {OldNamecall(self, ...)}
				LogRemote("RemoteFunction", self, "InvokeClient", args, returns)
				return unpack(returns)
			end
		end
		return OldNamecall(self, ...)
	end
	setreadonly(mt, true)
end

local function HookMethods()
	local RemoteEvent = game:GetService("RemoteEvent")
	local RemoteFunction = game:GetService("RemoteFunction")

	OldFireServer = hookfunction(RemoteEvent.FireServer, function(self, ...)
		LogRemote("RemoteEvent", self, "FireServer", {...})
		return OldFireServer(self, ...)
	end)

	OldFireClient = hookfunction(RemoteEvent.FireClient, function(self, ...)
		LogRemote("RemoteEvent", self, "FireClient", {...})
		return OldFireClient(self, ...)
	end)

	OldInvokeServer = hookfunction(RemoteFunction.InvokeServer, function(self, ...)
		local returns = {OldInvokeServer(self, ...)}
		LogRemote("RemoteFunction", self, "InvokeServer", {...}, returns)
		return unpack(returns)
	end)

	OldInvokeClient = hookfunction(RemoteFunction.InvokeClient, function(self, ...)
		local returns = {OldInvokeClient(self, ...)}
		LogRemote("RemoteFunction", self, "InvokeClient", {...}, returns)
		return unpack(returns)
	end)
end

-- Initialize
local function Initialize()
	HookNamecall()
	HookMethods()
	print("[SimpleSpy] Loaded v" .. SimpleSpy.Version .. " - Remote logging active")
	print("[SimpleSpy] Use SimpleSpy.GetLogs() to retrieve logs")
end

-- Public API
function SimpleSpy.GetLogs(remoteType)
	return SimpleSpy[remoteType] or {}
end

function SimpleSpy.ClearLogs(remoteType)
	if remoteType then
		SimpleSpy[remoteType] = {}
	else
		SimpleSpy.RemoteEvent = {}
		SimpleSpy.RemoteFunction = {}
	end
end

function SimpleSpy.SetConfig(key, value)
	if Config[key] ~= nil then
		Config[key] = value
	end
end

function SimpleSpy.GetConfig()
	return Config
end

-- Export to global
getgenv().SimpleSpy = SimpleSpy

Initialize()
"""

SIMPLESPY_TUTORIAL = r"""
-- =============================================
-- SimpleSpy v3.0.0 - Tutorial & Usage Guide
-- =============================================
--
-- QUICK START:
-- 1. Inject this script into your Roblox executor
-- 2. Or run via loadstring:
--    loadstring(game:HttpGet("https://pastefy.app/lYDYdOPY/raw"))()
--
-- AFTER INJECTION:
--   SimpleSpy is now logging all RemoteEvents and RemoteFunctions!
--
--   Access logs via:
--     SimpleSpy.GetLogs("RemoteEvent")  -- Returns table of RemoteEvent logs
--     SimpleSpy.GetLogs("RemoteFunction")  -- Returns table of RemoteFunction logs
--
--   Each log entry contains:
--     .Remote   - Full path to the remote (e.g. "ReplicatedStorage.RemoteEvent")
--     .Type     - "RemoteEvent" or "RemoteFunction"
--     .Method   - "FireServer", "FireClient", "InvokeServer", "InvokeClient"
--     .Args     - Table of serialized arguments
--     .Returns  - Table of return values (for Invoke*)
--     .Time     - Timestamp (HH:MM:SS)
--     .Tick     - High-precision tick()
--
-- EXAMPLE: Print all logged remotes to console
--   for _, log in ipairs(SimpleSpy.GetLogs("RemoteEvent")) do
--       print(log.Time, log.Remote, log.Method, unpack(log.Args))
--   end
--
-- EXAMPLE: Find specific remote by name
--   local function FindRemote(name)
--       for _, log in ipairs(SimpleSpy.GetLogs("RemoteEvent")) do
--           if log.Remote:find(name) then
--               print("Found:", log.Remote, log.Method)
--               print("Args:", unpack(log.Args))
--           end
--       end
--   end
--   FindRemote("Attack")  -- Finds remotes with "Attack" in name
--
-- EXAMPLE: Copy last remote args to clipboard
--   local logs = SimpleSpy.GetLogs("RemoteEvent")
--   if #logs > 0 then
--       local args = logs[1].Args
--       setclipboard(table.concat(args, ", "))
--       print("Copied args to clipboard!")
--   end
--
-- CONFIGURATION:
--   SimpleSpy.SetConfig("Enabled", false)  -- Disable logging
--   SimpleSpy.SetConfig("IgnoreSelf", false)  -- Log self-fired remotes
--   SimpleSpy.SetConfig("MaxLogs", 10000)  -- Increase log limit
--   SimpleSpy.SetConfig("AutoScroll", false)
--   SimpleSpy.SetConfig("ShowRemoteArgs", false)
--   SimpleSpy.SetConfig("ShowReturnValues", false)
--
--   print(SimpleSpy.GetConfig())  -- View current config
--
-- CLEAR LOGS:
--   SimpleSpy.ClearLogs()  -- Clear all
--   SimpleSpy.ClearLogs("RemoteEvent")  -- Clear only events
--
-- ADVANCED: Hook custom remotes
--   local myRemote = game.ReplicatedStorage.MyRemote
--   myRemote.OnClientEvent:Connect(function(...)
--       print("MyRemote fired:", ...)
--   end)
--
-- TROUBLESHOOTING:
--   - Requires executor with: hookfunction, getrawmetatable, getnamecallmethod, setclipboard
--   - Works on: Synapse X, Script-Ware, Fluxus, Krnl, Electron, etc.
--   - If logs not appearing: check Config.Enabled = true
--   - For high-volume games: increase MaxLogs or filter manually
--
-- SOURCE & UPDATES:
--   GitHub: https://github.com/exxtremestuffs/SimpleSpy
--   This build: MoonVeil Obfuscator v1.4.5
--   6Vms mirror: https://pastefy.app/lYDYdOPY/raw
--
-- =============================================
"""

def build_bytes():
    return SIMPLESPY_SOURCE + "\n\n" + SIMPLESPY_TUTORIAL

def build(out_path):
    full = build_bytes()
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(full)
    print("[6Vms] wrote {} ({} KB)".format(out_path, len(full) // 1024))

if __name__ == "__main__":
    p = argparse.ArgumentParser(description="6Vms SimpleSpy (RemoteSpy)")
    p.add_argument("output", nargs="?", default="simplespy.luau")
    a = p.parse_args()
    build(a.output)